// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Board struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Color     sql.NullString `json:"color"`
	Createdat sql.NullTime   `json:"createdat"`
	Accountid string         `json:"accountid"`
}

type Column struct {
	ID      string          `json:"id"`
	Name    string          `json:"name"`
	Order   sql.NullFloat64 `json:"order"`
	Boardid int64           `json:"boardid"`
}

type Item struct {
	ID       string         `json:"id"`
	Title    string         `json:"title"`
	Content  sql.NullString `json:"content"`
	Order    float64        `json:"order"`
	Columnid string         `json:"columnid"`
	Boardid  int64          `json:"boardid"`
}
