CREATE TABLE Account (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE NOT NULL
);

CREATE TABLE Password (
  id TEXT PRIMARY KEY,
  salt TEXT NOT NULL,
  hash TEXT NOT NULL,
  accountId TEXT UNIQUE NOT NULL,
  FOREIGN KEY (accountId) REFERENCES Account(id)
);

CREATE TABLE Board (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  color TEXT DEFAULT '#e0e0e0',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  accountId TEXT NOT NULL,
  FOREIGN KEY (accountId) REFERENCES Account(id)
);

CREATE TABLE Column (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  "order" REAL DEFAULT 0,
  boardId INTEGER NOT NULL,
  FOREIGN KEY (boardId) REFERENCES Board(id) ON DELETE CASCADE
);

CREATE TABLE Item (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  "order" REAL NOT NULL,
  columnId TEXT NOT NULL,
  boardId INTEGER NOT NULL,
  FOREIGN KEY (boardId) REFERENCES Board(id) ON DELETE CASCADE,
  FOREIGN KEY (columnId) REFERENCES Column(id) ON DELETE CASCADE
);
